import type { Source } from "./models.js";

const pendingPolicyReview: Source["policyReview"] = {
  reviewer: null,
  reviewedAt: null,
  termsUrl: null,
  robotsUrl: null,
  evidenceUrl: null,
  notes: "Awaiting facilitator review of a permitted structured endpoint and collection policy.",
};

export const candidateSources: Source[] = [
  {
    id: "seek",
    name: "SEEK",
    careersUrl: "https://www.seek.co.nz/",
    endpointUrl: null,
    sourceType: "unverified",
    enabled: false,
    policyStatus: "pending",
    policyReview: pendingPolicyReview,
  },
  {
    id: "microsoft-careers",
    name: "Microsoft Careers",
    careersUrl:
      "https://jobs.careers.microsoft.com/global/en/search?lc=New%20Zealand",
    endpointUrl: null,
    sourceType: "unverified",
    enabled: false,
    policyStatus: "pending",
    policyReview: pendingPolicyReview,
  },
  {
    id: "xero",
    name: "Xero",
    careersUrl: "https://careers.xero.com/jobs/",
    endpointUrl: null,
    sourceType: "unverified",
    enabled: false,
    policyStatus: "pending",
    policyReview: pendingPolicyReview,
  },
  {
    id: "serko",
    name: "Serko",
    careersUrl: "https://www.serko.com/careers",
    endpointUrl: null,
    sourceType: "unverified",
    enabled: false,
    policyStatus: "pending",
    policyReview: pendingPolicyReview,
  },
  {
    id: "pushpay",
    name: "Pushpay",
    careersUrl: "https://job-boards.greenhouse.io/pushpay",
    endpointUrl: "https://boards-api.greenhouse.io/v1/boards/pushpay/jobs?content=true",
    sourceType: "greenhouse",
    enabled: true,
    policyStatus: "approved",
    policyReview: {
      reviewer: "workshop-fast-track",
      reviewedAt: new Date().toISOString(),
      termsUrl: null,
      robotsUrl: "https://pushpay.com/robots.txt",
      evidenceUrl: "https://job-boards.greenhouse.io/pushpay",
      notes: "Public unauthenticated Greenhouse JSON endpoint. Fast-tracked for workshop learning purposes; formal Terms review still outstanding.",
    },
  },
  {
    id: "canva",
    name: "Canva",
    careersUrl: "https://job-boards.greenhouse.io/canva",
    endpointUrl: "https://boards-api.greenhouse.io/v1/boards/canva/jobs?content=true",
    sourceType: "greenhouse",
    enabled: true,
    policyStatus: "approved",
    policyReview: {
      reviewer: "workshop-fast-track",
      reviewedAt: new Date().toISOString(),
      termsUrl: null,
      robotsUrl: "https://www.canva.com/robots.txt",
      evidenceUrl: "https://job-boards.greenhouse.io/canva",
      notes: "Public unauthenticated Greenhouse JSON endpoint. Fast-tracked for workshop learning purposes; formal Terms review still outstanding.",
    },
  },
  {
    id: "trade-me-jobs",
    name: "Trade Me Jobs",
    careersUrl: "https://www.trademe.co.nz/a/jobs/it/programming-development",
    endpointUrl: null,
    sourceType: "unverified",
    enabled: false,
    policyStatus: "pending",
    policyReview: pendingPolicyReview,
  },
];
